export const HUMANINK_NATIVE_THEME = `
.humanink-native{height:100%;min-height:0;display:flex;flex-direction:column;gap:10px;padding:12px;color:var(--foreground,#24242a);background:var(--background,#fff);font:13px/1.45 system-ui,-apple-system,"Segoe UI",sans-serif;box-sizing:border-box}
.humanink-native *{box-sizing:border-box}.humanink-native button,.humanink-native input,.humanink-native textarea,.humanink-native select{font:inherit;color:inherit}
.humanink-native__header{display:flex;align-items:center;justify-content:space-between;gap:8px}.humanink-native__header>div{display:flex;align-items:baseline;gap:7px}.humanink-native__header strong{font-size:16px}.humanink-native__header span{color:var(--muted-foreground,#777);font-size:11px}.humanink-native__session{padding:3px 7px;border:1px solid var(--border,#ddd);border-radius:999px}.humanink-native__context{padding:4px 8px;border:1px dashed var(--border,#ddd);border-radius:6px;color:var(--muted-foreground,#777);font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.humanink-native__create{display:grid;grid-template-columns:1fr auto;gap:6px}.humanink-native__create input,.humanink-native__project,.humanink-native__title,.humanink-native__editor textarea{width:100%;border:1px solid var(--border,#ddd);background:var(--card,#fff);border-radius:7px;outline:none}.humanink-native__create input,.humanink-native__project,.humanink-native__title{height:34px;padding:0 10px}.humanink-native__create input:focus,.humanink-native__project:focus,.humanink-native__title:focus,.humanink-native__editor textarea:focus{border-color:#7545a4;box-shadow:0 0 0 2px color-mix(in srgb,#7545a4 15%,transparent)}
.humanink-native button{border:1px solid var(--border,#ddd);background:var(--card,#fff);border-radius:7px;padding:7px 10px;cursor:pointer}.humanink-native button:hover:not(:disabled){border-color:#7545a4;background:color-mix(in srgb,#7545a4 8%,var(--card,#fff))}.humanink-native button:disabled{opacity:.45;cursor:not-allowed}.humanink-native__create button{color:#fff;background:#7545a4;border-color:#7545a4}
.humanink-native__error{display:flex;flex-direction:column;gap:2px;padding:8px 10px;color:#9f2445;background:#fff1f4;border:1px solid #f1b7c5;border-radius:7px}.humanink-native__error span{word-break:break-word}
.humanink-native__workflow{display:grid;grid-template-columns:repeat(3,1fr);gap:6px}.humanink-native__workflow button:nth-child(5){color:#fff;background:#7545a4;border-color:#7545a4}
.humanink-native__editor{display:flex;flex:1;min-height:220px;flex-direction:column;gap:6px}.humanink-native__title{font-weight:650}.humanink-native__editor textarea{flex:1;min-height:180px;padding:10px;resize:none;line-height:1.65}
.humanink-native__actions{display:grid;grid-template-columns:1fr 1fr 1fr;gap:6px}.humanink-native__actions button:first-child{color:#fff;background:#7545a4;border-color:#7545a4}
.humanink-native__section-title{display:flex;justify-content:space-between;padding:2px 0}.humanink-native__section-title span{color:var(--muted-foreground,#777)}.humanink-native__tasks{display:flex;flex-direction:column;gap:5px}.humanink-native__task{display:grid;grid-template-columns:1fr auto;gap:2px 8px;padding:6px 8px;border-left:3px solid #aaa;background:var(--muted,#f6f6f7);border-radius:5px}.humanink-native__task.is-succeeded{border-left-color:#2f9c69}.humanink-native__task.is-failed{border-left-color:#cc3e61}.humanink-native__task.is-running{border-left-color:#7545a4}.humanink-native__task small{grid-column:1/-1;color:#9f2445;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.humanink-native__versions{border-top:1px solid var(--border,#ddd);padding-top:8px}.humanink-native__versions summary{cursor:pointer;font-weight:600}.humanink-native__versions button{width:100%;display:flex;justify-content:space-between;margin-top:5px;text-align:left}.humanink-native__versions button.is-active{border-color:#7545a4}.humanink-native__versions small,.humanink-native__empty{color:var(--muted-foreground,#777);font-size:11px}.humanink-native__empty{padding:8px;text-align:center}
`;
