export const HUMANINK_THEME = `
.humanink-overlay-screen {
  --hi-ink:#241f2b; --hi-muted:#777080; --hi-purple:#7152a5; --hi-purple-deep:#4d356f;
  --hi-purple-soft:#eee8f7; --hi-paper:#fbfaf7; --hi-panel:#fff; --hi-line:#e9e4ec;
  position:fixed; inset:0; z-index:1200; padding:18px; background:rgba(27,22,33,.48);
  backdrop-filter:blur(10px); color:var(--hi-ink); font-family:Inter,ui-sans-serif,system-ui,-apple-system,"PingFang SC","Microsoft YaHei",sans-serif;
}
.humanink-overlay-screen,.humanink-overlay-screen *{box-sizing:border-box}
.humanink-workbench{height:100%;min-height:620px;overflow:hidden;display:grid;grid-template-rows:66px minmax(0,1fr);border:1px solid rgba(255,255,255,.75);border-radius:22px;background:var(--hi-paper);box-shadow:0 24px 80px rgba(31,20,43,.22)}
.humanink-topbar{display:flex;align-items:center;justify-content:space-between;padding:0 20px 0 22px;border-bottom:1px solid var(--hi-line);background:rgba(255,255,255,.9)}
.humanink-brand{display:flex;align-items:center;gap:12px}.humanink-brandmark,.humanink-launch-mark{display:grid;place-items:center;color:#fff;background:linear-gradient(145deg,#8869ba,#4d356f);font-family:Georgia,serif}
.humanink-brandmark{width:34px;height:34px;border-radius:11px;box-shadow:0 8px 22px rgba(91,61,129,.26);font-size:18px}.humanink-brand strong{display:block;font:650 17px Georgia,"Songti SC",serif;letter-spacing:.04em}.humanink-brand small{display:block;color:var(--hi-muted);font-size:11px;margin-top:2px}
.humanink-top-actions,.humanink-segmented{display:flex;align-items:center;gap:8px}.humanink-save-state{color:var(--hi-muted);font-size:12px}
.humanink-layout{display:grid;grid-template-columns:258px minmax(420px,1fr) 326px;min-height:0}.humanink-rail,.humanink-assistant{min-height:0;overflow:auto;background:rgba(255,255,255,.72)}.humanink-rail{border-right:1px solid var(--hi-line);padding:18px 14px}.humanink-assistant{border-left:1px solid var(--hi-line);padding:18px}.humanink-editor{min-width:0;min-height:0;overflow:auto;padding:26px clamp(24px,4vw,64px) 46px;background:radial-gradient(circle at 50% 0%,rgba(239,233,248,.55),transparent 34%),var(--hi-paper)}
.humanink-section-head{display:flex;align-items:center;justify-content:space-between;gap:10px;margin:0 4px 12px}.humanink-section-head h2,.humanink-section-head h3{margin:0;color:var(--hi-muted);font-size:12px;letter-spacing:.12em;text-transform:uppercase}.humanink-list{display:grid;gap:7px;margin-bottom:24px}
.humanink-project,.humanink-version{width:100%;border:1px solid transparent;border-radius:12px;padding:11px 12px;background:transparent;color:var(--hi-ink);text-align:left;cursor:pointer;transition:.18s ease}.humanink-project:hover,.humanink-version:hover{background:#f3eff7}.humanink-project.is-active,.humanink-version.is-active{border-color:#dcd0ec;background:var(--hi-purple-soft);color:var(--hi-purple-deep)}.humanink-project strong{display:-webkit-box;overflow:hidden;-webkit-box-orient:vertical;-webkit-line-clamp:2;font-size:13px;line-height:1.45}.humanink-project small,.humanink-version small{display:block;margin-top:5px;color:var(--hi-muted);font-size:11px}.humanink-version{display:flex;align-items:center;justify-content:space-between;padding:9px 11px;font-size:12px}.humanink-version small{margin:0}
.humanink-new-row{display:grid;grid-template-columns:1fr auto;gap:7px;margin-bottom:10px}.humanink-input,.humanink-title-input,.humanink-body{width:100%;border:1px solid var(--hi-line);outline:none;color:var(--hi-ink);background:rgba(255,255,255,.84);transition:border-color .18s,box-shadow .18s}.humanink-input:focus,.humanink-title-input:focus,.humanink-body:focus{border-color:#a68acb;box-shadow:0 0 0 3px rgba(113,82,165,.1)}.humanink-input{height:38px;border-radius:10px;padding:0 11px;font-size:12px}.humanink-title-input{border:0;border-bottom:1px solid transparent;border-radius:0;padding:8px 0 14px;background:transparent;font:650 clamp(27px,3.2vw,42px)/1.28 Georgia,"Songti SC",serif}.humanink-title-input:focus{border-bottom-color:#c7b5dd;box-shadow:none}.humanink-document-meta{display:flex;align-items:center;justify-content:space-between;min-height:38px;margin-bottom:18px;color:var(--hi-muted);font-size:12px}.humanink-body,.humanink-preview{min-height:58vh;border:1px solid var(--hi-line);border-radius:15px;padding:24px 26px;background:rgba(255,255,255,.84);box-shadow:0 12px 36px rgba(47,35,58,.04);font:17px/2 Georgia,"Songti SC",serif}.humanink-body{resize:vertical}.humanink-preview p{margin:0 0 1.15em}.humanink-preview h1,.humanink-preview h2,.humanink-preview h3{color:var(--hi-purple-deep);line-height:1.45}
.humanink-btn{appearance:none;min-height:36px;border:1px solid var(--hi-line);border-radius:10px;padding:0 13px;background:#fff;color:var(--hi-ink);cursor:pointer;font-size:12px;font-weight:650;transition:transform .15s,border-color .15s}.humanink-btn:hover{transform:translateY(-1px);border-color:#c7b5dd}.humanink-btn:disabled{cursor:not-allowed;opacity:.5;transform:none}.humanink-btn-primary{border-color:var(--hi-purple);color:#fff;background:linear-gradient(145deg,#7d5bad,#5a3e7f)}.humanink-btn-quiet{background:transparent}.humanink-btn-icon{width:36px;padding:0;font-size:18px}.humanink-segmented{padding:3px;border:1px solid var(--hi-line);border-radius:11px;background:#f4f1f5}.humanink-segmented button{border:0;border-radius:8px;padding:7px 12px;background:transparent;color:var(--hi-muted);cursor:pointer;font-size:12px}.humanink-segmented button.is-active{background:#fff;color:var(--hi-purple-deep);box-shadow:0 2px 8px rgba(40,29,50,.08)}
.humanink-card{margin-bottom:13px;border:1px solid var(--hi-line);border-radius:15px;padding:15px;background:rgba(255,255,255,.86);box-shadow:0 8px 28px rgba(47,35,58,.035)}.humanink-card h3{margin:0 0 5px;font-size:14px}.humanink-card p{margin:0 0 13px;color:var(--hi-muted);font-size:12px;line-height:1.55}.humanink-workflow-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.humanink-workflow-grid .humanink-btn{min-height:42px}.humanink-task{display:grid;grid-template-columns:9px 1fr auto auto;align-items:center;gap:9px;padding:10px 0;border-top:1px solid #f0edf2;font-size:12px}.humanink-task:first-of-type{border-top:0}.humanink-dot{width:8px;height:8px;border-radius:999px;background:#b2a9bb}.humanink-dot.is-queued{background:#b08a38}.humanink-dot.is-running{background:var(--hi-purple);box-shadow:0 0 0 4px rgba(113,82,165,.12)}.humanink-dot.is-succeeded{background:#30745a}.humanink-dot.is-failed,.humanink-dot.is-cancelled{background:#a64355}.humanink-empty{padding:18px 8px;color:var(--hi-muted);text-align:center;font-size:12px}.humanink-error{margin:0 0 12px;border:1px solid #efd3d9;border-radius:10px;padding:10px 12px;background:#fff3f5;color:#a64355;font-size:12px}
.humanink-sidebar-launch{width:100%;display:flex;align-items:center;gap:9px;border:0;border-radius:10px;padding:9px 10px;background:transparent;color:inherit;cursor:pointer}.humanink-sidebar-launch:hover{background:rgba(113,82,165,.1)}.humanink-sidebar-launch.is-rail{justify-content:center;padding-inline:0}.humanink-launch-mark{width:25px;height:25px;flex:0 0 auto;border-radius:8px}
@media(max-width:1100px){.humanink-layout{grid-template-columns:220px minmax(420px,1fr)}.humanink-assistant{position:absolute;top:84px;right:18px;bottom:18px;z-index:3;width:316px;box-shadow:-14px 0 35px rgba(35,25,44,.12)}}
@media(max-width:760px){.humanink-overlay-screen{padding:0}.humanink-workbench{min-height:100%;border-radius:0}.humanink-layout{grid-template-columns:1fr}.humanink-rail,.humanink-assistant{display:none}.humanink-editor{padding:20px}.humanink-brand small,.humanink-save-state{display:none}}
`;
